"""empty message

Revision ID: 9c1c19938705
Revises: 
Create Date: 2018-04-16 23:43:57.381352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1c19938705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('watchedlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('film_title', sa.String(length=250), nullable=True),
    sa.Column('film_poster_path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchedlist_film_id'), 'watchedlist', ['film_id'], unique=False)
    op.create_index(op.f('ix_watchedlist_film_poster_path'), 'watchedlist', ['film_poster_path'], unique=False)
    op.create_index(op.f('ix_watchedlist_film_title'), 'watchedlist', ['film_title'], unique=False)
    op.create_index(op.f('ix_watchedlist_rating'), 'watchedlist', ['rating'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('film_title', sa.String(length=250), nullable=True),
    sa.Column('film_poster_path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_film_id'), 'watchlist', ['film_id'], unique=False)
    op.create_index(op.f('ix_watchlist_film_poster_path'), 'watchlist', ['film_poster_path'], unique=False)
    op.create_index(op.f('ix_watchlist_film_title'), 'watchlist', ['film_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_film_title'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_film_poster_path'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_film_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_watchedlist_rating'), table_name='watchedlist')
    op.drop_index(op.f('ix_watchedlist_film_title'), table_name='watchedlist')
    op.drop_index(op.f('ix_watchedlist_film_poster_path'), table_name='watchedlist')
    op.drop_index(op.f('ix_watchedlist_film_id'), table_name='watchedlist')
    op.drop_table('watchedlist')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
