"""empty message

Revision ID: e48d85c6f313
Revises: 
Create Date: 2018-04-07 14:06:19.946671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48d85c6f313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MPAA',
    sa.Column('mpaa_rating_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('mpaa_rating_id')
    )
    op.create_table('cast_crew',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True)
    )
    op.create_table('film_genres',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True)
    )
    op.create_table('film_keywords',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True)
    )
    op.create_table('films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('mpaa_rating_id', sa.Integer(), nullable=True),
    sa.Column('trailer_url', sa.String(length=100), nullable=True),
    sa.Column('poster_url', sa.String(length=100), nullable=True),
    sa.Column('synopsis', sa.String(length=600), nullable=True),
    sa.Column('runtime_mins', sa.Integer(), nullable=True),
    sa.Column('quality_rating', sa.Float(), nullable=True),
    sa.Column('on_netflix', sa.Boolean(), nullable=True),
    sa.Column('on_hulu', sa.Boolean(), nullable=True),
    sa.Column('amazon_cost', sa.Integer(), nullable=True),
    sa.Column('tmdb_poster_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('parent_genre_id', sa.Integer(), nullable=True),
    sa.Column('genre_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('keywords',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_table('people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('watched_list',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True)
    )
    op.create_table('watchlist',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('watched_list')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('people')
    op.drop_table('keywords')
    op.drop_table('jobs')
    op.drop_table('genres')
    op.drop_table('films')
    op.drop_table('film_keywords')
    op.drop_table('film_genres')
    op.drop_table('cast_crew')
    op.drop_table('MPAA')
    # ### end Alembic commands ###
